# Generated by Django 6.0.6 on 2026-07-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề / Yêu cầu câu hỏi')),
                ('level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Trắc nghiệm (4 đáp án)'), ('drag_drop_blank', 'Kéo thả điền khuyết (Medium)'), ('sort_code', 'Sắp xếp dòng code (Hard)')], default='multiple_choice', max_length=20)),
                ('code', models.TextField(blank=True, null=True, verbose_name='Đoạn mã hiển thị (Nếu có)')),
                ('option_a', models.CharField(blank=True, max_length=255, null=True)),
                ('option_b', models.CharField(blank=True, max_length=255, null=True)),
                ('option_c', models.CharField(blank=True, max_length=255, null=True)),
                ('option_d', models.CharField(blank=True, max_length=255, null=True)),
                ('correct_option', models.CharField(blank=True, max_length=1, null=True, verbose_name='Đáp án đúng (A/B/C/D)')),
                ('pool_answers', models.TextField(blank=True, null=True, verbose_name='Box chứa vô số đáp án (Cách nhau bởi dấu phẩy)')),
                ('blank_answers', models.CharField(blank=True, max_length=255, null=True, verbose_name='Các đáp án đúng theo thứ tự ô trống (Cách nhau bởi dấu phẩy)')),
                ('shuffled_lines', models.TextField(blank=True, null=True, verbose_name="Các dòng code lộn xộn bên trái (Cách nhau bởi '||')")),
                ('correct_lines_order', models.TextField(blank=True, null=True, verbose_name="Thứ tự các dòng code đúng hoàn chỉnh (Cách nhau bởi '||')")),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
