# Generated by Django 6.0.6 on 2026-07-05 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0003_gamequestion_delete_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointerGameQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tình huống / Chướng ngại vật')),
                ('level', models.IntegerField(choices=[(1, 'Chặng 1: Tokyo Cyber Highway (Easy)'), (2, 'Chặng 2: Neo Monaco GP (Medium)'), (3, 'Chặng 3: Hell Gate Nürburgring (Hard)')], default=1, verbose_name='Thuộc Chặng Level')),
                ('code_context', models.TextField(blank=True, null=True, verbose_name='Đoạn mã con trỏ mẫu (Nếu có)')),
                ('option_1', models.CharField(max_length=150, verbose_name='Đáp án 1')),
                ('option_2', models.CharField(max_length=150, verbose_name='Đáp án 2')),
                ('option_3', models.CharField(max_length=150, verbose_name='Đáp án 3')),
                ('option_4', models.CharField(max_length=150, verbose_name='Đáp án 4')),
                ('option_5', models.CharField(max_length=150, verbose_name='Đáp án 5')),
                ('option_6', models.CharField(max_length=150, verbose_name='Đáp án 6')),
                ('correct_option', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], verbose_name='Đáp án đúng (Từ 1 đến 6)')),
            ],
        ),
        migrations.CreateModel(
            name='PointerGameScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('has_won', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
